### ISSUE TITLE
Node version compatibility issue

### ISSUE THREAD

**Issue by Htsoul** [ipfs/js-kubo-rpc-client#190]
Low node version import error: 
node V14.16.1
import kuboClient from 'kubo-rpc-client';
`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:xxx\node_modules\kubo-rpc-client\dist\src\index.js
require() of ES modules is not supported`

high node version import success:
node V16.17.0

I have tried different versions of `kubo-rpc-client`, and there is a problem with `import` in lower versions of nodes, but in higher versions of nodes, there is no problem.

I think it should be a compatibility issue caused by the node version.

**Comment by rvalle** [comment]
I get the same error with Node 18 and 20

**Comment by achingbrain** [comment]
Only LTS node is supported (20 at the time of writing).

If you see this error, you may be authoring in TypeScript and using `import` statements, but your tsconfig may be set to output CJS, in which case you'll get this error.  If this is the case please update your settings to output ESM.
