### ISSUE TITLE
feat: provide example for kubo RPC auth

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/js-kubo-rpc-client#211]
Kubo just merged RPC auth support: https://github.com/ipfs/kubo/issues/10187 and we should make sure kubo-rpc-client has an example showing how users would talk to a Kubo that has enabled auth secret.

**Comment by hacdias** [comment]
Well, we kinda have the example already: https://github.com/ipfs/js-kubo-rpc-client#custom-headers 😅
