### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by prohtmlcoder** [ipfs/js-kubo-rpc-client#214]
Hi There, newbie here, trying to learn Web3 Stack.

Problem:

I am using the node version of this package. 

IPFS Version:ipfs version 0.20.0

I am starting the node in the offline mode using:

ipfs daemon -- offline

```
I am using Svelte in Routify boiler plate. 
Here is my code:

<script>
    import { create } from 'kubo-rpc-client'

let ipfs = 95;
async function check()
{
    ipfs = create({  host: 'localhost',  port: 5001,
    protocol: 'http',  headers: {    authorization: 'Basic ' + btoa('alice:password123')  }})
    for await (const chunk of ipfs.cat("QmfZpxN6pcNZar7zKU5DAhokXfE7bF2Ej89db5ZMEvxZwf"))// This file is existing in the IPFS
    {    console.info(chunk)    }
    
}
</script>
<button on:click={check}>Check</button>
{ipfs}
```

I am getting the following errors:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5001/api/v0/cat?arg=QmfZpxN6pcNZar7zKU5DAhokXfE7bF2Ej89db5ZMEvxZwf. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5001/api/v0/cat?arg=QmfZpxN6pcNZar7zKU5DAhokXfE7bF2Ej89db5ZMEvxZwf. (Reason: CORS request did not succeed). Status code: (null).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. 
```

What am I doing wrong, how can I improve. Please help, I am stuck on this for a very long time

Here is my config file:
[con.json](https://github.com/ipfs/js-kubo-rpc-client/files/14071798/con.json)

Thank you in advance.

**Comment by lidel** [comment]
Hi @prohtmlcoder,  we use github only for bugs and feature requests. 
In the future, please fill support questions like this at community forums at https://discuss.ipfs.tech/c/help/13

To get you started: 
- read about CORS at https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS 
- define necessary CORS headers in [`API.HTTPHeaders`](https://github.com/ipfs/kubo/blob/master/docs/config.md#apihttpheaders)
- if you have any further questions, please ask at https://discuss.ipfs.tech/c/help/13
