### ISSUE TITLE
ipfs-core-utils deprecation warning

### ISSUE THREAD

**Issue by nferch** [ipfs/js-kubo-rpc-client#219]
When installing a package that uses `kubo-rpc-client`, I get the following deprecation warning:

`npm WARN deprecated ipfs-core-utils@0.18.1: js-IPFS has been deprecated in favour of Helia - please see https://github.com/ipfs/js-ipfs/issues/4336 for details`

I (somewhat?) understand the situation with `js-ipfs` and migrated from `ipfs-http-client` as a result of this, so it was somewhat surprised to see this warning. It was my understanding that moving to this library was a recommended migration path for use cases that couldn't use Helia.

Is the long-term plan to remove this dependency so the deprecation warning is no longer displayed? Apologies if this is tracked or documented elsewhere!

**Comment by SgtPooki** [comment]
The long term plan is to remove/replace `ipfs-core-utils` in this library, but there are a *ton* of types to move over.

**Comment by achingbrain** [comment]
Fixed by #221 and released in `4.0.0`
