### ISSUE TITLE
Pull out relevant tests from interface-ipfs-core

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/js-kubo-rpc-client#5]
Originally from https://github.com/ipfs/kubo/issues/9125

~~Not an action item I feel comfortable deciding upon, so I'll leave this for @aschmahmann and @lidel for now.~~

Kubo RPC Client should have its own tests, stripped out from [interface-ipfs-core](https://github.com/ipfs/js-ipfs/tree/master/packages/interface-ipfs-core). And we should only bring over the tests that are applicable for Kubo's supported RPC calls. -- https://github.com/ipfs/kubo/issues/9125#issuecomment-1225001246

- [x] #48
- ~~[ ] #52~~
- ~~[ ] #53~~
- [ ] #56

**Comment by SgtPooki** [comment]
@achingbrain @lidel https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/test/interface.spec.js seems to be empty (had it's only line, `use strict`, removed by https://github.com/ipfs/js-ipfs/pull/3879).

If there are no tests in [that package](https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core), where should I look for moving old `ipfs-http-client` tests to this repo?

**Comment by BigLep** [comment]
@SgtPooki : do you have clarity now on where the relevant tests are?

**Comment by SgtPooki** [comment]
@BigLep not yet

**Comment by achingbrain** [comment]
When running tests using `ipfs-http-client` against `go-ipfs` the tests are loaded from https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/test/interface-http-go.js

The complete test suite is imported:

```js
import * as tests from 'interface-ipfs-core'
```

each member of tests is part of the test suite, you either run all the tests in that suite:

```js
tests.repo(commonFactory)
```

..or you skip some of the tests in the suite because there's been a divergence in the implementations:

```js
tests.root(commonFactory, {
    skip: [
      {
        name: 'should add with mode as string',
        reason: 'TODO not implemented in go-ipfs yet'
      },
      {
        name: 'should add with mode as number',
        reason: 'TODO not implemented in go-ipfs yet'
      },
      //... etc
```

Hopefully that helps.

**Comment by SgtPooki** [comment]
Thanks that helps.

**Comment by SgtPooki** [comment]
@BigLep Most of the reasons these are failing are due to dependency variations between the `ipfs` (js-ipfs) and `kubo-rpc-client` packages. I don't want to synchronize the dependencies, because that's one of the problems we're trying to escape from.

Others are less obvious: 
1. Are some tests depending on `proc` functionality that doesn't exist in `ipfs-http-client`/`kubo-rpc-client`? https://github.com/ipfs/js-kubo-rpc-client/commit/49fd3c09d064a445aff8d9fe3ceae11650fc1a5f
2. Are newer/changed dependencies in `kubo-rpc-client`, that may be locked in sub-packages of `ipfs`, causing failures like with https://github.com/ipfs/js-kubo-rpc-client/commit/32ebdee6f415393a155c811df223deab15d0d068 ?
3. Is it the upgrade to a newer `ipfsd-ctl` that wasn't done in `ipfs-http-client` prior to porting code into `kubo-rpc-client` like with https://github.com/ipfs/js-kubo-rpc-client/commit/05346a1b175119d7520e0a30885b0db86d7a5d22, where the `.id()` returns an instance of a PeerID instead of a string?

I'm discovering more as I go, but all the changes I've made thus far are at https://github.com/ipfs/js-kubo-rpc-client/compare/master...52-remove-tests-that-are-skipped

My current plan is to continue what I've been doing: fixing simple/obvious/trivial failures, and spend no more than 30 minutes on failures I can't resolve myself.

There are 708 tests ran in `node` environment, 705 ran in `browser` environment, and 705 ran in `webworker` environment. Spending too much time on any of these feels like the wrong thing.

**Comment by SgtPooki** [comment]
Also, there may be a number of tests that could* have been enabled months/years ago that weren't: https://github.com/ipfs/js-kubo-rpc-client/commit/565ed0808ab5bc8293ae31ba364304649ba9c7c8

I'm also testing those when doing so isn't time-prohibitive.

**Comment by SgtPooki** [comment]
one particularly troublesome library that i'm now officially marking as broken during transition has to do with using the `iso-random-stream` library, where we use `randomBytes` to write file content, and then try to read that content from ipfs, and ensure that they're equal. The way the tests are currently written, many of these (4 so far) are failing with things like `expected Buffer[ 235, 46, 147, 191, 105, …(308) ] to deeply equal Readable{ …(6), …(1) }`

---
```
1) kubo-rpc-client tests against Kubo
       .files.cp
         copies a file to new location:
     AssertionError: expected Buffer[ 105, 130, 20, 193, 1, 6, …(389) ] to deeply equal Readable{ …(6), …(1) }
      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/files/cp.js:144:29)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  2) kubo-rpc-client tests against Kubo
       .files.mv
         moves a file:
     AssertionError: expected Buffer[ 235, 46, 147, 191, 105, …(308) ] to deeply equal Readable{ …(6), …(1) }
      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/files/mv.js:59:29)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  3) kubo-rpc-client tests against Kubo
       .files.read
         reads a small file:
     AssertionError: expected Buffer[ 233, 149, 147, 85, 19, …(-12) ] to deeply equal Readable{ …(6), …(1) }
      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/files/read.js:44:29)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      
  30) kubo-rpc-client tests against Kubo
       .files.write
         rewrites really big files:
     AssertionError: expected Buffer[ 11, 140, 199, 227, 94, …(307071) ] to deeply equal Readable{ …(6), …(1) }
      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/files/write.js:492:35)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I imagine @achingbrain could probably provide insight on these, but I'm moving on for now.

**Comment by SgtPooki** [comment]
per discussion in kubo standup today: I'm trying to ensure deps are synced in kubo-rpc-client to the deps resolved when running interface-http-go tests from `js-ipfs/packages/ipfs`,
* need to manually resolve dependencies between  `js-ipfs/packages/ipfs`, `/packages/interface-ipfs-core`, and `/packages/ipfs-http-client` to the dependencies that existed when `kubo-rpc-client` was pulled out of `ipfs-http-client`

**Comment by SgtPooki** [comment]
Using `https://github.com/ipfs/js-ipfs/releases/tag/ipfs-v0.64.2` npm install isn't working on https://github.com/ipfs/js-ipfs/commit/39dbf708ec31b263115e44f420651fa4e056a89e

**Comment by SgtPooki** [comment]
Update of status provided in original tracking issue for kubo rpc client work: https://github.com/ipfs/kubo/issues/9125#issuecomment-1337936966
