### ISSUE TITLE
Skip (but leave) tests that were being skipped in interface-ipfs-core 

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/js-kubo-rpc-client#52]
some tests are skipped in https://github.com/ipfs/js-kubo-rpc-client/blob/c899abbc32d0f46b55fdda896c6f32240b49d1c6/test/interface-tests.spec.js

Skip them using https://github.com/ipfs/js-kubo-rpc-client/blob/c899abbc32d0f46b55fdda896c6f32240b49d1c6/test/constants.js#L16 instead

Some of these tests that are skipped looked like they should have been removed from the skip list a while ago, and I think leaving that determination up to Kubo team is the right call.

**Comment by BigLep** [comment]
> Some of these tests that are skipped looked like they should have been removed from the skip list a while ago, and I think leaving that determination up to Kubo team is the right call.

@SgtPooki : when you say removed from the skip list, do you mean that they should be enabled or be deleted?

**Comment by SgtPooki** [comment]
superseded by https://github.com/ipfs/js-kubo-rpc-client/issues/56
