### ISSUE TITLE
 update docs to mention only js-kubo-rpc-client and kuboRpcModule

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/js-kubo-rpc-client#6]
Originally from https://github.com/ipfs/kubo/issues/9125

  - [x] #35
  - [x] #36
  - [x] #37

**Comment by lidel** [comment]
I believe we need to also go over examples in this repo:
-  https://github.com/ipfs-examples/js-ipfs-examples/tree/master/examples

At the very list, eyeballs things that mention [go-ipfs](https://github.com/ipfs-examples/js-ipfs-examples/search?q=go-ipfs) and [kubo](https://github.com/ipfs-examples/js-ipfs-examples/search?q=kubo).
